version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - postgres
    volumes:
      - .:/app
      - ./src:/app/src
      - ./node_modules:/app/node_modules
