services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FRAMEWORK=${FRAMEWORK:-nest}
      - PORT=${PORT:-3000}
      - MONGO_URL=mongodb://root:password@mongo:27017/app?authSource=admin
      - DATABASE_URL=postgres://admin:admin@postgres:5432/triumph
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
        - target: 5432
          published: ${POSTGRES_PORT:-5432}
          protocol: tcp
    environment:
        POSTGRES_DB: ${POSTGRES_DB:-triumph}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
        POSTGRES_USER: ${POSTGRES_USER:-admin}
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    ports:
        - "8080:8080"
    environment:
        - ADMINER_DEFAULT_SERVER=postgres
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
        - "127.0.0.1:27017:27017"
    volumes:
        - mongo-data:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped

volumes:
    mongo-data: {}
    postgres_data: {}