services:
    mongo:
        image: mongo
        ports:
            - "127.0.0.1:27017:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: unless-stopped

volumes:
    mongo-data: {}