services:
    nest:
        build:
            context: ./src/infrastructure/frameworks/nest
            dockerfile: Dockerfile
        environment:
            - PORT=3001
            - MONGO_URL=mongodb://root:password@mongo:27017/app?authSource=admin
            - DATABASE_URL=postgres://root:password@postgres:5432/app
            - JWT_SECRET=secret
            - MAILER_SERVICE=Gmail
            - MAILER_HOST=smtp.gmail.com
            - MAILER_PORT=465
            - BASE_URL=http://localhost:3001
            - NODE_ENV=development
        ports:
            - "127.0.0.1:3001:3001"
        volumes:
            - ./src/infrastructure/frameworks/nest:/app/nest
